name: JandySimpleTransfer
main: org.jandy.JandySimpleTransfer.main
version: 1.0.0
author: jandy
commands:
  tpa:
    description: abc
    usage: /tpa
  tpaccept:
    description: abc
    usage: /tpaccept
  tpdeny:
    description: abc
    usage: /tpdeny
